//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 15 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")
    /// Color `prime`.
    static let prime = Rswift.ColorResource(bundle: R.hostingBundle, name: "prime")
    /// Color `text_gray1`.
    static let text_gray1 = Rswift.ColorResource(bundle: R.hostingBundle, name: "text_gray1")
    /// Color `text_gray2`.
    static let text_gray2 = Rswift.ColorResource(bundle: R.hostingBundle, name: "text_gray2")
    /// Color `text_gray3`.
    static let text_gray3 = Rswift.ColorResource(bundle: R.hostingBundle, name: "text_gray3")
    /// Color `text_gray4`.
    static let text_gray4 = Rswift.ColorResource(bundle: R.hostingBundle, name: "text_gray4")
    /// Color `text_gray5`.
    static let text_gray5 = Rswift.ColorResource(bundle: R.hostingBundle, name: "text_gray5")
    /// Color `view_able1`.
    static let view_able1 = Rswift.ColorResource(bundle: R.hostingBundle, name: "view_able1")
    /// Color `view_able_no1`.
    static let view_able_no1 = Rswift.ColorResource(bundle: R.hostingBundle, name: "view_able_no1")
    /// Color `view_background`.
    static let view_background = Rswift.ColorResource(bundle: R.hostingBundle, name: "view_background")
    /// Color `view_gray1`.
    static let view_gray1 = Rswift.ColorResource(bundle: R.hostingBundle, name: "view_gray1")
    /// Color `view_gray2`.
    static let view_gray2 = Rswift.ColorResource(bundle: R.hostingBundle, name: "view_gray2")
    /// Color `view_gray3`.
    static let view_gray3 = Rswift.ColorResource(bundle: R.hostingBundle, name: "view_gray3")
    /// Color `view_gray4`.
    static let view_gray4 = Rswift.ColorResource(bundle: R.hostingBundle, name: "view_gray4")
    /// Color `view_gray5`.
    static let view_gray5 = Rswift.ColorResource(bundle: R.hostingBundle, name: "view_gray5")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "prime", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func prime(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.prime, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "text_gray1", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func text_gray1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.text_gray1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "text_gray2", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func text_gray2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.text_gray2, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "text_gray3", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func text_gray3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.text_gray3, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "text_gray4", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func text_gray4(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.text_gray4, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "text_gray5", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func text_gray5(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.text_gray5, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "view_able1", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func view_able1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.view_able1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "view_able_no1", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func view_able_no1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.view_able_no1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "view_background", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func view_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.view_background, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "view_gray1", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func view_gray1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.view_gray1, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "view_gray2", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func view_gray2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.view_gray2, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "view_gray3", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func view_gray3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.view_gray3, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "view_gray4", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func view_gray4(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.view_gray4, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "view_gray5", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func view_gray5(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.view_gray5, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "prime", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func prime(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.prime.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "text_gray1", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func text_gray1(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.text_gray1.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "text_gray2", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func text_gray2(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.text_gray2.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "text_gray3", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func text_gray3(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.text_gray3.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "text_gray4", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func text_gray4(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.text_gray4.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "text_gray5", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func text_gray5(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.text_gray5.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "view_able1", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func view_able1(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.view_able1.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "view_able_no1", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func view_able_no1(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.view_able_no1.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "view_background", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func view_background(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.view_background.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "view_gray1", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func view_gray1(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.view_gray1.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "view_gray2", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func view_gray2(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.view_gray2.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "view_gray3", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func view_gray3(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.view_gray3.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "view_gray4", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func view_gray4(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.view_gray4.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "view_gray5", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func view_gray5(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.view_gray5.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `CityCode.json`.
    static let cityCodeJson = Rswift.FileResource(bundle: R.hostingBundle, name: "CityCode", pathExtension: "json")
    /// Resource file `area.plist`.
    static let areaPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "area", pathExtension: "plist")

    /// `bundle.url(forResource: "CityCode", withExtension: "json")`
    static func cityCodeJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cityCodeJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "area", withExtension: "plist")`
    static func areaPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.areaPlist
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 2 images.
  struct image {
    /// Image `cry100`.
    static let cry100 = Rswift.ImageResource(bundle: R.hostingBundle, name: "cry100")
    /// Image `navi_back`.
    static let navi_back = Rswift.ImageResource(bundle: R.hostingBundle, name: "navi_back")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "cry100", bundle: ..., traitCollection: ...)`
    static func cry100(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.cry100, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "navi_back", bundle: ..., traitCollection: ...)`
    static func navi_back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navi_back, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"
            static let uiSceneStoryboardFile = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneStoryboardFile") ?? "Main"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 5 nibs.
  struct nib {
    /// Nib `CommNavigationBar`.
    static let commNavigationBar = _R.nib._CommNavigationBar()
    /// Nib `JYDatePickerViewController`.
    static let jyDatePickerViewController = _R.nib._JYDatePickerViewController()
    /// Nib `SLNoNetworkViewController`.
    static let slNoNetworkViewController = _R.nib._SLNoNetworkViewController()
    /// Nib `SLNoNetworkView`.
    static let slNoNetworkView = _R.nib._SLNoNetworkView()
    /// Nib `SLVisitorViewController`.
    static let slVisitorViewController = _R.nib._SLVisitorViewController()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "CommNavigationBar", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.commNavigationBar) instead")
    static func commNavigationBar(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.commNavigationBar)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "JYDatePickerViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.jyDatePickerViewController) instead")
    static func jyDatePickerViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.jyDatePickerViewController)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SLNoNetworkView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.slNoNetworkView) instead")
    static func slNoNetworkView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.slNoNetworkView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SLNoNetworkViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.slNoNetworkViewController) instead")
    static func slNoNetworkViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.slNoNetworkViewController)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SLVisitorViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.slVisitorViewController) instead")
    static func slVisitorViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.slVisitorViewController)
    }
    #endif

    static func commNavigationBar(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> CommNavigationBar? {
      return R.nib.commNavigationBar.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? CommNavigationBar
    }

    static func jyDatePickerViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.jyDatePickerViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func slNoNetworkView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SLNoNetworkView? {
      return R.nib.slNoNetworkView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SLNoNetworkView
    }

    static func slNoNetworkViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.slNoNetworkViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func slVisitorViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.slVisitorViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try nib.validate()
    #endif
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _CommNavigationBar.validate()
      try _SLNoNetworkViewController.validate()
      try _SLVisitorViewController.validate()
    }

    struct _CommNavigationBar: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "CommNavigationBar"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> CommNavigationBar? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? CommNavigationBar
      }

      static func validate() throws {
        if UIKit.UIImage(named: "navi_back", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'navi_back' is used in nib 'CommNavigationBar', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _JYDatePickerViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "JYDatePickerViewController"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      fileprivate init() {}
    }

    struct _SLNoNetworkView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SLNoNetworkView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SLNoNetworkView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SLNoNetworkView
      }

      fileprivate init() {}
    }

    struct _SLNoNetworkViewController: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "SLNoNetworkViewController"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      static func validate() throws {
        if UIKit.UIImage(named: "cry100", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'cry100' is used in nib 'SLNoNetworkViewController', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "text_gray2", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text_gray2' is used in nib 'SLNoNetworkViewController', but couldn't be loaded.") }
          if UIKit.UIColor(named: "view_able1", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'view_able1' is used in nib 'SLNoNetworkViewController', but couldn't be loaded.") }
          if UIKit.UIColor(named: "view_background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'view_background' is used in nib 'SLNoNetworkViewController', but couldn't be loaded.") }
        }
      }

      fileprivate init() {}
    }

    struct _SLVisitorViewController: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "SLVisitorViewController"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      static func validate() throws {
        if UIKit.UIImage(named: "cry100", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'cry100' is used in nib 'SLVisitorViewController', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "text_gray2", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'text_gray2' is used in nib 'SLVisitorViewController', but couldn't be loaded.") }
          if UIKit.UIColor(named: "view_able1", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'view_able1' is used in nib 'SLVisitorViewController', but couldn't be loaded.") }
          if UIKit.UIColor(named: "view_background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'view_background' is used in nib 'SLVisitorViewController', but couldn't be loaded.") }
        }
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try main.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = ViewController

      let bundle = R.hostingBundle
      let name = "Main"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
